[package]
name = "fil-read-parent-cache"
version = "0.1.0"
edition = "2021"


[dependencies]
storage-proofs-core = "16.1.0"

anyhow = "1"
memmap2 = "0.5.6"
byteorder = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.7"
